apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: default    # remove or adjust if you use a different namespace
type: Opaque
stringData:
  # mysqld-exporter’s client config file
  .my.cnf: |
    [client]
    user=root
    password=root
    host=mysql-summary-records
    port=3306
    database=summary_db

  # MongoDB exporter URI
  mongodb-uri: "mongodb://root:password@mongodb:27017/admin?authSource=admin"
