apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: staging
type: Opaque
data:
  username: c3VwZXJ1c2Vy  # Base64 encoded 'superuser'
  password: c3VwZXJzZWNyZXQ=  # Base64 encoded 'supersecret'
