{
 "title": "Database Recovery System",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "infra_cpu_usage_percent", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "infra_mem_usage_percent", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Chaos Events by Type",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chaos_event_count", "legendFormat": "{{event_type}}" }
   ]
  },
  {
   "title": "Seconds Since Last Chaos Event",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "seconds_since_last_chaos_event\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Metrics Scraped",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "infra_metric_total_scrapes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Chaos Experiment Running?",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chaos_experiment_running", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Absolute Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Cores" } },
   "targets": [
    { "expr": "infra_cpu_usage_absolute", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "Memory Absolute Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    { "expr": "infra_mem_usage_absolute", "legendFormat": "{{pod}}" }
   ]
  }
 ]
}