apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
data:
  grafana-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        orgId: 1
        url: http://prometheus:80
        isDefault: true
        version: 1
        editable: true
