apiVersion: v1
data:
  init_db.sql: "CREATE DATABASE IF NOT EXISTS summary_db;\r\nUSE summary_db;\r\n\r\nCREATE
    TABLE IF NOT EXISTS infra_metrics (\r\n    id INT AUTO_INCREMENT PRIMARY KEY,\r\n
    \   timestamp DATETIME,\r\n    source VARCHAR(100),\r\n    cpu_percent FLOAT,\r\n
    \   cpu_used FLOAT,\r\n    mem_percent FLOAT,\r\n    mem_used FLOAT,\r\n    node_name
    VARCHAR(100),\r\n    pod_name VARCHAR(100),\r\n    pod_namespace VARCHAR(100)\r\n);\r\n"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: mysql-init-script
