apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: mysql-exporter
        metrics_path: /metrics
        static_configs:
          - targets: ['mysqld-exporter:9104']

      - job_name: mongodb-exporter
        metrics_path: /metrics
        static_configs:
          - targets: ['mongodb-exporter:9216']
