apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      # —————————————————————————————
      # 1) keep your existing k8s-pod-annotation job
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__meta_kubernetes_pod_ip, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            target_label: __address__
            regex: ([^;]+);(\d+)
            replacement: $1:$2

      # —————————————————————————————
      # 2) static scrape for MySQL exporter
      - job_name: 'mysql-exporter'
        metrics_path: /metrics
        static_configs:
          - targets: ['mysqld-exporter:9104']

      # —————————————————————————————
      # 3) static scrape for MongoDB exporter
      - job_name: 'mongodb-exporter'
        metrics_path: /metrics
        static_configs:
          - targets: ['mongodb-exporter:9216']
