apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-proxy-app
  labels:
    app: python-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-proxy
  template:
    metadata:
      labels:
        app: python-proxy
    spec:
      containers:
        - name: python-proxy-container
          image: lukasmccain0/capstone-app:latest
          imagePullPolicy: Always 
          ports:
            - name: tcp-proxy
              containerPort: 3307
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password
          livenessProbe:
            tcpSocket:
              port: 3307
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3307
            initialDelaySeconds: 5
            periodSeconds: 5
