apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-exporter
  labels:
    app: capstone-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-exporter
  template:
    metadata:
      labels:
        app: capstone-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: capstone-exporter
          image: lucasbaker905/capstone-exporter:latest
          ports:
            - containerPort: 5000
          env:
            - name: MYSQL_HOST
              value: "mysql-summary-records"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              value: "root"
            - name: MYSQL_DB
              value: "summary_db"
