# k8s/deployments/mongodb-exporter-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-exporter
  labels:
    app: mongodb-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-exporter
  template:
    metadata:
      labels:
        app: mongodb-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port:   "9216"
        prometheus.io/path:   "/metrics"
    spec:
      containers:
        - name: mongodb-exporter
          image: bitnami/mongodb-exporter:latest
          env:
            - name: MONGODB_URI
              # root:password@mongodb:27017  → adjust to your creds/secret
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: mongodb-uri
          ports:
            - containerPort: 9216
