# ----------------------------------------
# PRIMARY MYSQL DATABASE (mysql-primary)
# ----------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-primary
  labels:
    app: mysql
    role: primary
spec:
  serviceName: mysql-primary
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      role: primary
  template:
    metadata:
      labels:
        app: mysql
        role: primary
    spec:
      containers:
        - name: mysql
          image: lukasmccain0/mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
            - name: MYSQL_DATABASE
              value: "capstone_db"
            - name: MYSQL_ROOT_HOST
              value: "%"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
# ----------------------------------------
# REPLICA MYSQL DATABASE (mysql-replica)
# ----------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-replica
  labels:
    app: mysql
    role: replica
spec:
  serviceName: mysql-replica
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      role: replica
  template:
    metadata:
      labels:
        app: mysql
        role: replica
    spec:
      containers:
        - name: mysql
          image: lukasmccain0/mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
            - name: MYSQL_DATABASE
              value: "capstone_db"
            - name: MYSQL_ROOT_HOST
              value: "%"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---

# ----------------------------------------
# SUMMARY MYSQL DATABASE (mysql-summary-records)
# ----------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-summary-records
  labels:
    app: mysql-summary-records
spec:
  serviceName: mysql-summary-records
  replicas: 1
  selector:
    matchLabels:
      app: mysql-summary-records
  template:
    metadata:
      labels:
        app: mysql-summary-records
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_ROOT_HOST
              value: "%"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/init_db.sql
              subPath: init_db.sql
      volumes:
        - name: init-script
          configMap:
            name: mysql-init-script
        - name: mysql-data
          emptyDir: {}