# This file is for all of our services to monitor our database recovery application
apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  containers:
    - name: zookeeper
      image: confluentinc/cp-zookeeper:6.1.1
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"
      env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
      livenessProbe:
        tcpSocket:
          port: 2181
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        tcpSocket:
          port: 2181
        initialDelaySeconds: 10
        periodSeconds: 5

    - name: apache-kafka
      image: apache/kafka:latest
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"
      livenessProbe:
        tcpSocket:
          port: 9092
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        tcpSocket:
          port: 9092
        initialDelaySeconds: 10
        periodSeconds: 5

    - name: mongo-db
      image: mongo:latest
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"
      livenessProbe:
        exec:
          command: ["mongo", "--eval", "db.runCommand({ ping: 1 })"]
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        exec:
          command: ["mongo", "--eval", "db.runCommand({ ping: 1 })"]
        initialDelaySeconds: 10
        periodSeconds: 5

    - name: mysql
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "admin"  
      resources:
        requests:
          memory: "512Mi"
          cpu: "500m"
        limits:
          memory: "1Gi"
          cpu: "1"
      livenessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        tcpSocket:
          port: 3306
        initialDelaySeconds: 10
        periodSeconds: 5

    - name: jenkins
      image: jenkins/jenkins:lts
      args: ["--httpPort=8081"]
      ports:
        - containerPort: 8081
      resources:
        requests:
          memory: "1Gi"
          cpu: "500m"
        limits:
          memory: "2Gi"
          cpu: "1"
      livenessProbe:
        httpGet:
          path: /login
          port: 8081
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /login
          port: 8081
        initialDelaySeconds: 10
        periodSeconds: 5


    - name: grafana
      image: grafana/grafana:latest
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
          cpu: "500m"
      livenessProbe:
        httpGet:
          path: /api/health
          port: 3000
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /api/health
          port: 3000
        initialDelaySeconds: 10
        periodSeconds: 5

    - name: prometheus
      image: prom/prometheus:latest
      resources:
        requests:
          memory: "256Mi"
          cpu: "250m"
        limits:
          memory: "512Mi"
         
