apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    app: app
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      nodePort: 30080
  type: NodePort
