apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
  labels:
    app: kafka-nodeport
spec:
  type: NodePort
  ports:
    - name: external-kafka
      port: 9092
      targetPort: 9092  
      nodePort: 30092    
      protocol: TCP
  selector:
    app: kafka