apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      name: external
      targetPort: 9092
    - port: 9093
      name: controller
      targetPort: 9093
    - port: 9094
      name: internal
      targetPort: 9094
  clusterIP: None
  selector:
    app: kafka
  publishNotReadyAddresses: true 