apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  ports:
    - port: 9092
      name: kafka
    - port: 9093
      name: controller
  clusterIP: None  # Headless service
  selector:
    app: kafka