# k8s/services/mongodb-exporter-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  labels:
    app: mongodb-exporter
spec:
  selector:
    app: mongodb-exporter
  ports:
    - name: metrics
      port: 9216
      targetPort: 9216
  type: ClusterIP
