apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  clusterIP: None
  selector:
    app: mysql
    role: primary 
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-replica
spec:
  clusterIP: None
  selector:
    app: mysql
    role: replica
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
