apiVersion: v1
kind: Service
metadata:
  name: mysql-primary
spec:
  clusterIP: None
  selector:
    app: mysql
    role: primary
  ports:
    - port: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-replica
spec:
  clusterIP: None
  selector:
    app: mysql
    role: replica
  ports:
    - port: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-summary-records
spec:
  clusterIP: None
  selector:
    app: mysql-summary-records
  ports:
    - port: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-summary-records
spec:
  clusterIP: None     
  selector:
    app: mysql-summary-records
  ports:
    - port: 3306

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-summary-records
spec:
  clusterIP: None
  selector:
    app: mysql-summary-records
  ports:
    - port: 3306
