apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-summary-records
  labels:
    app: mysql-summary-records
spec:
  serviceName: mysql-summary-records
  replicas: 1
  selector:
    matchLabels:
      app: mysql-summary-records
  template:
    metadata:
      labels:
        app: mysql-summary-records
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_ROOT_HOST
              value: "%"
            - name: MYSQL_DATABASE
              value: "summary_db"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: init-script
          configMap:
            name: mysql-init-script
        - name: mysql-data
          emptyDir: {}