# ----------------------------------------
# PRIMARY MYSQL DATABASE (mysql-primary)
# ----------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-primary
  labels:
    app: mysql
    role: primary
spec:
  serviceName: mysql-primary
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      role: primary
  template:
    metadata:
      labels:
        app: mysql
        role: primary
    spec:
      containers:
        - name: mysql
          image: lukasmccain0/mysql-primary:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
            - name: MYSQL_DATABASE
              value: "capstone_db"
            - name: MYSQL_ROOT_HOST
              value: "%"
          args:
            - "--gtid-mode=ON"
            - "--enforce-gtid-consistency=ON"
            - "--log-bin=mysql-bin"
            - "--server-id=1"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
# ----------------------------------------
# REPLICA MYSQL DATABASE (mysql-replica)
# ----------------------------------------
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-replica
  labels:
    app: mysql
    role: replica
spec:
  serviceName: mysql-replica
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      role: replica
  template:
    metadata:
      labels:
        app: mysql
        role: replica
    spec:
      containers:
        - name: mysql
          image: lukasmccain0/mysql-replica:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "admin"
            - name: MYSQL_DATABASE
              value: "capstone_db"
            - name: MYSQL_ROOT_HOST
              value: "%"
          args:
            - "--gtid-mode=ON"
            - "--enforce-gtid-consistency=ON"
            - "--log-bin=mysql-bin"
            - "--server-id=2"
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
